/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab.pkg040825;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;

class Student {

    private String id;
    private String name;
    private int age;
    private String major;
    private double gpa;
    private String nickName;

    Student(String id, String name, int age, String major, double gpa, String nickName) {
        this.id = id;
        this.name = name;
        this.age = age;
        this.major = major;
        this.gpa = gpa;
        this.nickName = nickName;
    }

    @Override
    public String toString() {
        return id + "," + name + "," + age + "," + major + "," + gpa + "," + nickName;
    }
}

public class StudentUI extends javax.swing.JFrame {

    public static Student[] students;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StudentUI.class.getName());

    public StudentUI() {
        initComponents();
//
//        Student[] students = new Student[5];
//        students[0] = new Student("6701", "A", 20, "CS", 3.89, "a");
//        students[1] = new Student("6702", "B", 20, "CS", 4.00, "b");
//        students[2] = new Student("6703", "H", 20, "IT", 3.89, "h");
//        students[3] = new Student("6704", "C", 20, "IT", 3.99, "c");
//        students[4] = new Student("6705", "D", 20, "IT", 3.65, "d");

//        for (int i = 0; i < students.length; ++i) {
//            System.out.println(students[i].toString());
//        }
//        
//        try {
//            FileWriter fileWriter = new FileWriter("data.txt");
//            PrintWriter printWriter = new PrintWriter(fileWriter);
//            for (Student x : students) {
//                printWriter.println(x.toString());
//            }
//            fileWriter.close();
//            printWriter.close();
//
//        } catch (Exception e) {
//        }
//        Student[] q = new Student[5];
//        try {
//            FileReader fileReader = new FileReader("data.txt");
//            BufferedReader reader = new BufferedReader(fileReader);
//
//            for (int i = 0; i < 5; ++i) {
//                String[] str = reader.readLine().split(",");
//                String id = str[0];
//                String name = str[1];
//                int age = Integer.parseInt(str[2]);
//                String major = str[3];
//                double gpa = Double.parseDouble(str[4]);
//                String nickname = str[5];
//                q[i] = new Student(id, name, age, major, gpa, nickname);
//            }
//            reader.close();
//            fileReader.close();
//        } catch (Exception e) {
//        }
//
//        for (Student i : q) {
//            System.out.println(i);
//        }
//        Student[] q = new Student[5];
//        try {
//            FileReader fileReader = new FileReader("data.txt");
//            BufferedReader reader = new BufferedReader(fileReader);
//
//            for (int i = 0; i < 5; i++) {
//                String[] str = reader.readLine().split(",");
//                String id = str[0];
//                String name = str[1];
//                int age = Integer.parseInt(str[2]);
//                String major = str[3];
//                double gpa = Double.parseDouble(str[4]);
//                String nickName = str[5];
//                q[i] = new Student(id, name, age, major, gpa, nickName);
//            }
//            reader.close();
//            fileReader.close();
//        } catch (Exception e) {
//        }
//
//        for (Student i : q) {
//            System.out.println(i);
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Load");
        jButton1.setActionCommand("Load");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("next");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("previous");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jButton1)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(116, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // load Button
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        students = new Student[5];
        try {
            FileReader fileReader = new FileReader("data.txt");
            BufferedReader reader = new BufferedReader(fileReader);

            for (int i = 0; i < 5; i++) {
                String[] str = reader.readLine().split(",");
                String id = str[0];
                String name = str[1];
                int age = Integer.parseInt(str[2]);
                String major = str[3];
                double gpa = Double.parseDouble(str[4]);
                String nickName = str[5];
                students[i] = new Student(id, name, age, major, gpa, nickName);
            }
            reader.close();
            fileReader.close();
        } catch (Exception e) {
        }
        String[] str = students[0].toString().split(",");

        jTextArea1.setText("ID: " + str[0] + "\n" + str[1] + "\n" + str[2] + "\n" + str[3] + "\n" + str[4] + "\n" + str[5]);


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(() -> new StudentUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
