/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab.pkg04082025;

import java.io.FileWriter;
import java.io.PrintWriter;

import java.io.FileReader;
import java.io.BufferedReader;

class Student {

    private String id;
    private String name;
    private int age;
    private String major;
    private double gpa;
    private String nickname;

    Student(String id, String name, int age, String major, double gpa, String nickname) {
        this.id = id;
        this.name = name;
        this.age = age;
        this.major = major;
        this.gpa = gpa;
        this.nickname = nickname;
    }

    public String toString() {
        return id + "," + name + "," + age + "," + major + "," + gpa + "," + nickname;
    }
}

public class NewJFrame extends javax.swing.JFrame {

    public static Student[] students;

    public NewJFrame() {
        initComponents();

        Student[] st = new Student[5];
        st[0] = new Student("6701", "A", 20, "CS", 3.99, "a");
        st[1] = new Student("6702", "B", 21, "IT", 3.55, "b");
        st[2] = new Student("6703", "C", 19, "CS", 3.09, "c");
        st[3] = new Student("6704", "D", 20, "IT", 2.58, "d");
        st[4] = new Student("6705", "E", 21, "CS", 2.04, "e");

        try {
            FileWriter fileWriter = new FileWriter("data.txt");
            PrintWriter printWriter = new PrintWriter(fileWriter);
            for (Student x : st) {
                printWriter.println(x.toString());
            }
            printWriter.close();
        } catch (Exception e) {

        }

        Student[] q = new Student[5];
        try {
            FileReader read = new FileReader("data.txt");
            BufferedReader reader = new BufferedReader(read);

            for (int i = 0; i < 5; ++i) {
                String[] str = reader.readLine().split(", ");
                String id = str[0];
                String name = str[1];
                int age = Integer.parseInt(str[2]);
                String major = str[3];
                double gpa = Double.parseDouble(str[4]);
                String nickname = str[5];

                q[i] = new Student(id, name, age, major, gpa, nickname);
            }
            read.close();
            reader.close();
        } catch (Exception e) {

        }
        for (Student i : q) {
            System.out.println(i);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Load");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton2.setText("Previous");

        jButton3.setText("Next");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(145, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // LOAD
        
                 students = new Student[5];
        try {
            FileReader read = new FileReader("data.txt");
            BufferedReader reader = new BufferedReader(read);

            for (int i = 0; i < 5; ++i) {
                String[] str = reader.readLine().split(",");
                String id = str[0];
                String name = str[1];
                int age = Integer.parseInt(str[2]);
                String major = str[3];
                double gpa = Double.parseDouble(str[4]);
                String nickname = str[5];

                students[i] = new Student(id, name, age, major, gpa, nickname);
            }
            read.close();
            reader.close();
        } catch (Exception e) {

        }
        for (Student i : students) {
            System.out.println(i);
        }
        jTextArea1.setText(students[0].toString);
    }//GEN-LAST:event_jButton1ActionPerformed
    /*
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
